### ISSUE TITLE
The comments datasets

### ISSUE THREAD

**Issue by zwanah** [raphael-sch/OverpassNL#1]
Good job! Could you pls provide comments datasets? Also, the download speed of the OpenStreetMap database is too slow.Could you pls provide another public cloud drive for me to download? Thanks a lot！

**Comment by raphael-sch** [comment]
I added the code comments instances here:
https://github.com/raphael-sch/OverpassNL/tree/main/dataset

Do you have a recommendation where I can upload and publish the OSM snapshot free of cost?

**Comment by zwanah** [comment]
Thanks a lot! I successfully downloaded it.

**Comment by zwanah** [comment]
![11181710176993_ pic_副本](https://github.com/raphael-sch/OverpassNL/assets/103487661/8c1448f0-c256-48f9-b799-7a311e2d5b88)
It seems that a file is missing from a compressed package. The size of the extracted "nodes_attic.bin" file is 9.11GB. Could you please confirm if this file size matches the original file on your end? I want to ensure that no data has been lost or corrupted during the download process. 

I would greatly appreciate your prompt response and any assistance you can provide in resolving this matter. Thank you for your time and consideration.

**Comment by raphael-sch** [comment]
this is the size of nodes_attic.bin:
18546311168 May  4  2023 nodes_attic.bin

The md5 is:
md5sum overpass_clone_db/db/nodes_attic.bin
c6b2ac0770143e11a061f9a4fd1c3b2a  overpass_clone_db/db/nodes_attic.bin


But I also work on re-uploading the dump in multiple splits to make it more convenient to download.

**Comment by zwanah** [comment]
Thank u for your response and look forward to the new data set download path！

**Comment by raphael-sch** [comment]
this is the new link (10 parts): https://www.cl.uni-heidelberg.de/~rschuman/files/overpassnl/db_dump/

**Comment by zwanah** [comment]
Thanks!
