### ISSUE TITLE
OpenStreetMap database

### ISSUE THREAD

**Issue by kongmingze** [raphael-sch/OverpassNL#2]
Hi! Thank you for your hard work! I've encountered an issue where it seems that the compressed file for the OSM database might be partially missing, as I'm unable to successfully extract it. Would it be possible for you to provide a new compressed file for download?

**Comment by raphael-sch** [comment]
I am working on re-uploading the dump in multiple splits to make it more convenient to download

**Comment by raphael-sch** [comment]
this is the new link (10 parts): https://www.cl.uni-heidelberg.de/~rschuman/files/overpassnl/db_dump/

**Comment by kongmingze** [comment]
Looking forward to using. Thank you very much!
